### PR TITLE
reformat the logger

### PR DESCRIPTION
**Pull request by michael-je**
Reformatting the logger to be more human readable and provide more information.

Pushing as a draft for now, I'd like to hear what you think.

### CODE REVIEW

**Comment by morgaesis** [comment]
In my experience with logging, the things you care about in your logs are: time, level, message.

Function name and line number (and even module name) don't really matter and will only make the log line longer.

Module name can, however, be useful in that it tells you whether the log message is from *your* program or some library. This can usually be deduced from context, though.

**Comment by michael-je** [comment]
That's fair. I think what I really want are different logs to be sent to a file and stderr, maybe even different log levels too. Reason being that I want more info in the console while debugging.
I want to be able to do this without having to make a custom logger though...

**Comment by morgaesis** [comment]
If that is your goal we could add a command line flag when starting the bot and set the log level accordingly.

```python
import argparse
parser = argparse.ArgumentParser(description="This is The Lone Dancer")
parser.add_argument("-v", action="count", default=0)
log_level = logging.ERROR - parser.v*10  # make error the default
```
See [docs](https://docs.python.org/3/library/logging.html#logging-levels) for list of numerical values for the log levels.

**Comment by thorduragust** [comment]
We can always just try out logging with line numbers and stuff to see how it looks like... I like the idea of having a command line flag, maybe something like --verbose_logging or something?

**Comment by morgaesis** [comment]
I'll whip up a PR with command line flags `--verbose` and `-v`, where each repetition increases verbosity, to a max `-vvv`.

**Comment by michael-je** [comment]
This PR is obsolete due to #63.

**Pull request closed without merging**
